### ISSUE TITLE
format_length returns incorrect value

### ISSUE THREAD

**Issue by ilobilo** [seanmiddleditch/nanofmt#49]
I'm trying to make print() function with nanofmt but format_length returns incorrect value.
string I'm trying to format is: ("{0} = 0x{0:X} = 0b{0:b}\n", 28) which is 11 characters if we remove {}s.
format_length returns 11 too but it should be 20
so instead of "28 = 0x1C = 0b11100\n" it prints "28 = 0x1C ="
```c++
template<typename ...Args>
auto print(nanofmt::format_string fmt, Args &&...args) -> size_t
{
    size_t length = nanofmt::format_length(fmt, std::forward<Args>(args)...);
    auto buffer = std::make_unique<char[]>(length + 1);
    auto end = nanofmt::format_to_n(buffer.get(), length, fmt, std::forward<Args>(args)...);
    buffer[end - buffer.get()] = 0;
    puts(buffer.get());
    return length;
}
/* ... */
print("{0} = 0x{0:X} = 0b{0:b}\n", length);
```
Btw idk why but if I do this it works fine:
```c++
print("{}, {} from {}!\n", "Hello"s, "World"sv, "kernelv2");
```

**Comment by seanmiddleditch** [comment]
Hmm. It looks like `format_int_impl` incorrectly calculates the length of the temporary buffer as the _available_ length rather than the length of the buffer. So in length calculation, where we have no buffer, nothing is written into the temporary buffer, and so there's nothing to count.

Definitely some missing test coverage here for this to have been missed!
